
export const PST_PROCESSANDO_POST = 'PST_PROCESSANDO_POST'
export const PST_PROCESSANDO_COMENTARIO = 'PST_PROCESSANDO_COMENTARIO'
export const PST_GET_POST = 'PST_GET_POST'
export const PST_GET_COMENTARIO = 'PST_GET_COMENTARIO'
